config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :reconcile_transactions do
    resources :summaries do
      collection do
        get :general_summary
      end
      member do
        get :export_discrepancies
      end
    end

    member do
      get :imported_data
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_row.rb
class DataRow < ApplicationRecord
  belongs_to :file_import

  enum row_type: [:header, :row]
end

app/models/destination_file.rb
class DestinationFile < ApplicationRecord
  has_paper_trail
  has_one_attached :destination

  # has_many :file_imports

  belongs_to :reconcile_transaction
end

app/models/file_import.rb
class FileImport < ApplicationRecord
  has_many :data_rows, dependent: :destroy

  belongs_to :reconcile_transaction

  enum import_type: [:source, :destination]
end

app/models/reconcile_transaction.rb
class ReconcileTransaction < ApplicationRecord
  has_paper_trail

  has_many :summaries, dependent: :destroy
  has_many :file_imports, dependent: :destroy

  has_many :source_files, dependent: :destroy
  accepts_nested_attributes_for :source_files, reject_if: :all_blank, allow_destroy: true

  has_many :destination_files, dependent: :destroy
  accepts_nested_attributes_for :destination_files, reject_if: :all_blank, allow_destroy: true
end

app/models/source_file.rb
class SourceFile < ApplicationRecord
  has_paper_trail
  has_one_attached :source

  # has_many :file_imports

  belongs_to :reconcile_transaction
end

app/models/summary.rb
class Summary < ApplicationRecord
  has_paper_trail

  belongs_to :reconcile_transaction

  enum summary_type: [:general, :custom]

  def discrepancies_to_csv
    discrepancies_data = self.detail_data['general']['reconcile-discrepancies']
    attributes = discrepancies_data.map(&:keys).flatten.uniq

    CSV.generate(headers: true) do |csv|
      csv << attributes

      discrepancies_data.present? && discrepancies_data.each do |discrepancy|
        csv << attributes.map{ |attr| discrepancy[attr] }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/reconcile_transactions_controller.rb
class ReconcileTransactionsController < ApplicationController
  before_action :set_reconcile_transaction, only: [:show, :imported_data]
  before_action :invalid_file_type, only: [:imported_data]

  def index
    @reconcile_transactions = ReconcileTransaction.all.order(created_at: :desc)
  end

  def new
    @reconcile_transaction = ReconcileTransaction.new
    @reconcile_transaction.source_files.build
    @reconcile_transaction.destination_files.build
  end

  def create
    @reconcile_transaction = ReconcileTransaction.new(reconcile_transaction_params)

    if @reconcile_transaction.save!
      ProcessReconcileTransactionData.perform_now(@reconcile_transaction.id)
      redirect_to reconcile_transaction_summaries_path(@reconcile_transaction)
    else
      render :new
    end
  end

  def show
    @source_files      = @reconcile_transaction.source_files
    @destination_files = @reconcile_transaction.destination_files
  end

  def imported_data
    @file_type    = params[:file_type]
    @file_imports = @reconcile_transaction.file_imports.includes(:data_rows)
  end

  private

  def set_reconcile_transaction
    @reconcile_transaction = ReconcileTransaction.find_by(id: params[:id])
  end

  def invalid_file_type
    redirect_to root_path if params[:file_type].blank?
  end

  def reconcile_transaction_params
    params.require(:reconcile_transaction).permit(
      source_files_attributes: [:source, :_destroy], destination_files_attributes: [:destination, :_destroy])
  end
end

app/controllers/summaries_controller.rb
require 'will_paginate/array'

class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :create_general_summary, :export_discrepancies]
  before_action :set_reconcile_transaction

  def index
    @summaries = Summary.all
  end

  def new
    @summary             = Summary.new
    @source_options      = DataRow.header.where(file_import_id: @reconcile_transaction.file_imports.source.ids).pluck(:values).compact.flatten.uniq
    @destination_options = DataRow.header.where(file_import_id: @reconcile_transaction.file_imports.destination.ids).pluck(:values).compact.flatten.uniq
  end

  def create
    @summary                          = Summary.new(summary_params)
    @summary.reconcile_transaction_id = @reconcile_transaction.id

    if @summary.save!
      CreateSummaryDetails.perform_now(@summary.id, @reconcile_transaction.id, 'custom')
      redirect_to reconcile_transaction_summary_path(@reconcile_transaction, @summary)
    else
      render :new
    end
  end

  def general_summary
    source_options      = DataRow.header.where(file_import_id: @reconcile_transaction.file_imports.source.ids).pluck(:values).compact.flatten.uniq
    destination_options = DataRow.header.where(file_import_id: @reconcile_transaction.file_imports.destination.ids).pluck(:values).compact.flatten.uniq

    @summary                          = Summary.new
    @summary.source_columns           = source_options
    @summary.destination_columns      = destination_options
    @summary.reconcile_transaction_id = @reconcile_transaction.id

    if @summary.save!
      CreateSummaryDetails.perform_now(@summary.id, @reconcile_transaction.id, 'general')
      redirect_to reconcile_transaction_summary_path(@reconcile_transaction, @summary)
    else
      redirect_to reconcile_transaction_summaries_path(@reconcile_transaction)
    end
  end

  def show
  end

  def export_discrepancies
    respond_to do |format|
      format.html
      format.csv { send_data @summary.discrepancies_to_csv, filename: "discrepancy-summary-#{DateTime.current.strftime("%F-%T")}.csv" }
    end
  end

  private

  def set_summary
    @summary = Summary.find_by(id: params[:id])
  end

  def set_reconcile_transaction
    @reconcile_transaction = ReconcileTransaction.find_by(id: params[:reconcile_transaction_id])
  end

  def summary_params
    params["summary"]["source_columns"]      = params["summary"]["source_columns"].reject(&:blank?)
    params["summary"]["result_columns"]      = params["summary"]["result_columns"].reject(&:blank?)
    params["summary"]["destination_columns"] = params["summary"]["destination_columns"].reject(&:blank?)
    params.require(:summary).permit(source_columns: [], destination_columns: [], result_columns: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(controller_name)
    case controller_name
    when 'reconcile_transactions'
      'Reconciliations'
    when 'dashboard'
      'Home'
    when 'summaries'
      'Summaries'
    end
  end
end

app/views/dashboard/index.html.erb
<div class="row justify-content-center">
  <div class="col-lg-4 col-md-12">
    <div class="white-box analytics-info">
      <h3 class="box-title">Total Reconciliations</h3>
      <ul class="list-inline two-part d-flex align-items-center mb-0">
        <li>
          <div id="sparklinedash"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas>
          </div>
        </li>
        <li class="ms-auto"><span class="counter text-success"><%= ReconcileTransaction.count %></span></li>
      </ul>
    </div>
  </div>
  <div class="col-lg-4 col-md-12">
    <div class="white-box analytics-info">
      <h3 class="box-title">Total Files</h3>
      <ul class="list-inline two-part d-flex align-items-center mb-0">
        <li>
          <div id="sparklinedash2"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas>
          </div>
        </li>
        <li class="ms-auto"><span class="counter text-purple"><%= (SourceFile.count + DestinationFile.count) %></span></li>
      </ul>
    </div>
  </div>
  <div class="col-lg-4 col-md-12">
    <div class="white-box analytics-info">
      <h3 class="box-title">Total Summaries</h3>
      <ul class="list-inline two-part d-flex align-items-center mb-0">
        <li>
          <div id="sparklinedash3"><canvas width="67" height="30" style="display: inline-block; width: 67px; height: 30px; vertical-align: top;"></canvas>
          </div>
        </li>
        <li class="ms-auto"><span class="counter text-info">0</span>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIB Reconcile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%#= render partial: 'layouts/shared/preloader' %>

    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
      <%= render partial: 'layouts/shared/header' %>
      <%= render partial: 'layouts/shared/sidebar' %>
      <div class="page-wrapper">
        <div class="page-breadcrumb bg-white">
          <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h4 class="page-title"><%= page_title(params[:controller]) %></h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
              <div class="d-md-flex">
                <ol class="breadcrumb ms-auto">
                  <li></li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="container-fluid">
          <%= yield %>
        </div>
        <%= render partial: 'layouts/shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="footer text-center">
  2021 © MIB Admin
</footer>

app/views/layouts/shared/_header.html.erb
<header class="topbar" data-navbarbg="skin5">
  <nav class="navbar top-navbar navbar-expand-md navbar-dark">
    <div class="navbar-header" data-logobg="skin6">
      <a class="navbar-brand" href="dashboard.html">
        <b class="logo-icon">
          <%= image_tag 'logo-icon.png', alt: 'homepage' %>
        </b>
        <span class="logo-text">
          <%= image_tag 'logo-text.png', alt: 'homepage' %>
        </span>
      </a>
      <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none" href="javascript:void(0)">
        <i class="ti-menu ti-close"></i>
      </a>
    </div>
    <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
      <ul class="navbar-nav ms-auto d-flex align-items-center">
        <li>
          <a class="profile-pic" href="#">
            <%= image_tag 'users/varun.jpg', alt: 'user-img', width: '36', class: 'img-circle' %>
            <span class="text-white font-medium">Shaheer</span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/shared/_preloader.html.erb
<div class="preloader">
  <div class="lds-ripple">
    <div class="lds-pos"></div>
    <div class="lds-pos"></div>
  </div>
</div>

app/views/layouts/shared/_sidebar.html.erb
<aside class='left-sidebar' data-sidebarbg='skin6'>
  <div class='scroll-sidebar'>
    <nav class='sidebar-nav'>
      <ul id='sidebarnav'>
        <li class='sidebar-item pt-2'>
          <%= link_to root_path, class: 'sidebar-link waves-effect waves-dark sidebar-link', 'aria-expanded' => 'false' do %>
            <i class='fa fa-home' aria-hidden='true'></i>
            <span class='hide-menu'>Home</span>
          <% end %>
        </li>
        <li class='sidebar-item pt-2'>
          <%= link_to reconcile_transactions_path, class: 'sidebar-link waves-effect waves-dark sidebar-link', 'aria-expanded' => 'false' do %>
            <i class='fa fa-files-o' aria-hidden='true'></i>
            <span class='hide-menu'>Reconciliations</span>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/reconcile_transactions/_destination_file_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.file_field :destination, class: 'form-control' %>
  </div>
  <%= link_to_remove_association '', f, class: 'fa fa-trash btn btn-danger float-right mt-3 mb-3' %>
</div>

app/views/reconcile_transactions/_source_file_fields.html.erb
<div class='nested-fields mt-2'>
  <div class="field">
    <%= f.file_field :source, class: 'form-control' %>
  </div>
  <%= link_to_remove_association '', f, class: 'fa fa-trash btn btn-danger float-right mt-3 mb-3' %>
</div>

app/views/reconcile_transactions/imported_data.html.erb
<% if @file_type == 'source' %>
  <div class="row">
    <div class="col-md-12">
      <div class="white-box">
        <div class='row'>
          <div class="col-md-10">
            <h3 class="box-title">Source Files</h3>
          </div>
          <div class="col-md-2">
          </div>
        </div>
        <% @file_imports.source.each do |file_import| %>
          <% header = file_import.data_rows.header.last.values %>
          <div class="row">
            <div class="col-sm-12">
              <div class="white-box">
                <div class="table-responsive">
                  <table class="table text-nowrap">
                    <thead>
                      <tr>
                        <th>#</th>
                        <% header.each do |heading| %>
                          <th class="border-top-0"><%= heading.titleize %></th>
                        <% end %>
                      </tr>
                    </thead>
                    <tbody>
                      <% file_import.data_rows.row.last(10).each.with_index(1) do |row, index| %>
                        <tr>
                          <th><%= index %></th>
                          <% row.values.each do |value| %>
                            <th><%= value %></th>
                          <% end %> 
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% elsif @file_type == 'destination' %>
  <div class="row">
    <div class="col-md-12">
      <div class="white-box">
        <div class='row'>
          <div class="col-md-10">
            <h3 class="box-title">Destination Files</h3>
          </div>
          <div class="col-md-2">
          </div>
        </div>
        <% @file_imports.source.each do |file_import| %>
          <% header = file_import.data_rows.header.last.values %>
          <div class="row">
            <div class="col-sm-12">
              <div class="white-box">
                <div class="table-responsive">
                  <table class="table text-nowrap">
                    <thead>
                      <tr>
                        <th>#</th>
                        <% header.each do |heading| %>
                          <th class="border-top-0"><%= heading.titleize %></th>
                        <% end %>
                      </tr>
                    </thead>
                    <tbody>
                      <% file_import.data_rows.row.last(10).each.with_index(1) do |row, index| %>
                        <tr>
                          <th><%= index %></th>
                          <% row.values.each do |value| %>
                            <th><%= value %></th>
                          <% end %> 
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-12">
      <div class="white-box">
        <div class='row'>
          <div class="col-md-10">
            <h3 class="box-title">Destination Files</h3>
          </div>
          <div class="col-md-2">
          </div>
        </div>
        <% @file_imports.source.each do |file_import| %>
          <% header = file_import.data_rows.header.last.values %>
          <div class="row">
            <div class="col-sm-12">
              <div class="white-box">
                Now Preview Available
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/reconcile_transactions/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class='row'>
        <div class="col-md-10">
          <h3 class="box-title">All Reconciliations</h3>
        </div>
        <div class="col-md-2">
          <%= link_to new_reconcile_transaction_path, class: 'btn btn-primary float-right' do %>
            <i class='fa fa-plus'></i> New Reconciliation
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="white-box">
            <div class="table-responsive">
              <table class="table text-nowrap">
                <thead>
                  <tr>
                    <th class="border-top-0">#</th>
                    <th class="border-top-0">Created At</th>
                    <th class="border-top-0">Summaries</th>
                    <th class="border-top-0">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @reconcile_transactions.each.with_index(1) do |reconcile_transaction, index| %>
                    <tr>
                      <th><%= index %></th>
                      <th><%= reconcile_transaction.created_at.strftime('%F at %I:%M') %></th>
                      <th>
                        <%= link_to reconcile_transaction_summaries_path(reconcile_transaction), class: 'btn btn-primary' do %>
                          <i class='fa fa-list'></i>
                        <% end %>
                      </th>
                      <th>
                        <%= link_to reconcile_transaction_path(reconcile_transaction), class: 'btn btn-warning' do %>
                          <i class='fa fa-eye'></i>
                        <% end %>
                        <%= link_to reconcile_transaction_path(reconcile_transaction), method: :delete, class: 'btn btn-danger' do %>
                          <i class='fa fa-trash'></i>
                        <% end %>
                      </th>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reconcile_transactions/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class='row'>
        <div class="col-md-10">
          <h3 class="box-title">New Reconciliation</h3>
        </div>
        <div class="col-md-2">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="white-box">
            <%= form_for @reconcile_transaction do |rt| %>
              <%= label_tag 'Source Files:' %>
              <div class='row'>
                <div class='col-md-12'>
                  <div id='source_files'>
                    <div class='row p-0'>
                      <div class='col-md-12'>
                        <%= rt.fields_for :source_files do |sf| %>
                          <%= render partial: 'source_file_fields', locals: {f: sf} %>
                        <% end %>
                        <div class='links float-right mr-2'>
                          <%= link_to_add_association '', rt, :source_files, class: 'fa fa-plus btn btn-warning float-left mt-3' %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <br>
              <%= label_tag 'Destination Files:' %>
              <div class='row'>
                <div class='col-md-12'>
                  <div id='destination_files'>
                    <div class='row p-0'>
                      <div class='col-md-12'>
                        <%= rt.fields_for :destination_files do |df| %>
                          <%= render partial: 'destination_file_fields', locals: {f: df} %>
                        <% end %>
                        <div class='links float-right mr-2'>
                          <%= link_to_add_association '', rt, :destination_files, class: 'fa fa-plus btn btn-warning float-left mt-3' %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class='col-sm-12 float-right mt-2 p-0'>
                <%= rt.submit 'Upload for Reconciliation', class: 'btn btn-primary float-right' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reconcile_transactions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class='row'>
        <div class="col-md-10">
          <h3 class="box-title">Source Files</h3>
        </div>
        <div class="col-md-2">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="white-box">
            <div class="table-responsive">
              <table class="table text-nowrap">
                <thead>
                  <tr>
                    <th class="border-top-0">#</th>
                    <th class="border-top-0">File Name</th>
                    <th class="border-top-0">Uploaded At</th>
                    <th class="border-top-0">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @source_files.each.with_index(1) do |source_file, index| %>
                    <tr>
                      <th><%= index %></th>
                      <th>
                        <%= source_file.source.blob.filename.to_s %>
                      </th>
                      <th><%= source_file.created_at.strftime('%F at %I:%M') %></th>
                      <th>
                        <%= link_to imported_data_reconcile_transaction_path(@reconcile_transaction, file_type: 'source'), class: 'btn btn-warning' do %>
                          <i class='fa fa-eye'></i>
                        <% end %>
                      </th>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class='row'>
        <div class="col-md-10">
          <h3 class="box-title">Destination Files</h3>
        </div>
        <div class="col-md-2">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="white-box">
            <div class="table-responsive">
              <table class="table text-nowrap">
                <thead>
                  <tr>
                    <th class="border-top-0">#</th>
                    <th class="border-top-0">File Name</th>
                    <th class="border-top-0">Uploaded At</th>
                    <th class="border-top-0">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @destination_files.each.with_index(1) do |destination_file, index| %>
                    <tr>
                      <th><%= index %></th>
                      <th>
                        <%= destination_file.destination.blob.filename.to_s %>
                      </th>
                      <th><%= destination_file.created_at.strftime('%F at %I:%M') %></th>
                      <th>
                        <%= link_to imported_data_reconcile_transaction_path(@reconcile_transaction, file_type: 'destination'), class: 'btn btn-warning' do %>
                          <i class='fa fa-eye'></i>
                        <% end %>
                      </th>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/summaries/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class='row'>
        <div class="col-md-6">
          <%= link_to new_reconcile_transaction_summary_path, class: 'btn btn-primary' do %>
            <i class='fa fa-plus'></i> New Custom Summary
          <% end %>
        </div>
        <div class="col-md-6">
          <%= link_to general_summary_reconcile_transaction_summaries_path(@reconcile_transaction), class: 'btn btn-info float-right' do %>
            <i class='fa fa-plus'></i> New General Summary
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="white-box">
            <div class="table-responsive">
              <table class="table text-nowrap">
                <thead>
                  <tr>
                    <th class="border-top-0">#</th>
                    <th class="border-top-0">Created At</th>
                    <th class="border-top-0">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @summaries.each.with_index(1) do |summary, index| %>
                    <tr>
                      <th><%= index %></th>
                      <th><%= summary.created_at.strftime('%F at %I:%M') %></th>
                      <th>
                        <%= link_to reconcile_transaction_summary_path(@reconcile_transaction, summary), class: 'btn btn-warning' do %>
                          <i class='fa fa-eye'></i>
                        <% end %>
                      </th>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/summaries/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class='row'>
        <div class="col-md-10">
          <h3 class="box-title">Create New Summary</h3>
        </div>
        <div class="col-md-2">
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="white-box">
            <%= form_for @summary, url: reconcile_transaction_summaries_path(@reconcile_transaction), method: :post do |s| %>
              <div class='col-sm-12 float-right mt-2 p-0'>
                <%= s.label :source_columns, 'Matching Source Points' %>
                <%= s.select :source_columns, options_for_select(@source_options.map { |sos| [sos.tr("_"," ").humanize, sos] }, []), {}, class: 'form-control select2-enable', multiple: true %>
              </div>
              <div class='col-sm-12 float-right mt-2 p-0'>
                <%= s.label :destination_columns, 'Matching Destination Points' %>
                <%= s.select :destination_columns, options_for_select(@destination_options.map { |dos| [dos.tr("_"," ").humanize, dos] }, []), {}, class: 'form-control select2-enable', multiple: true %>
              </div>
              <div class='col-sm-12 float-right mt-2 p-0'>
                <%= s.label :result_columns, 'Set Out Come Points' %>
                <%= s.select :result_columns, options_for_select(@destination_options.map { |dos| [dos.tr("_"," ").humanize, dos] }, []), {}, class: 'form-control select2-enable', multiple: true %>
              </div>
              <div class='col-sm-12 float-right mt-2 p-0'>
                <%= s.submit 'Save', class: 'btn btn-primary float-right' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/summaries/show.html.erb
<% if @summary.present? && @summary.detail_data.present? %>
  <% @summary.detail_data.map do |k, value_data| %>
    <% if k == 'source' %>
      <div class="row">
        <div class="col-md-12">
          <div class="white-box">
            <div class='row'>
              <div class="col-md-12">
                <h3 class="box-title">
                  <%= k.humanize %>
                </h3>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <div class="white-box">
                  <span>Source File Entries: <%= value_data['total-count'] %></span>
                  <br>
                  <span>Total Amount By Entries: <%= value_data['total-amount'] %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% elsif k == 'destination' %>
      <div class="row">
        <div class="col-md-12">
          <div class="white-box">
            <div class='row'>
              <div class="col-md-12">
                <h3 class="box-title">
                  <%= k.humanize %>
                </h3>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <div class="white-box">
                  <span>Source File Entries: <%= value_data['total-count'] %></span>
                  <br>
                  <span>Total Amount Entries: <%= value_data['total-amount'] %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% elsif k == 'general' %>
      <div class="row">
        <div class="col-md-12">
          <div class="white-box">
            <div class='row'>
              <div class="col-md-6">
                <h3 class="box-title">
                  <%= k.humanize %>
                </h3>
              </div>
              <div class="col-md-6">
                <%= link_to export_discrepancies_reconcile_transaction_summary_path(@reconcile_transaction.id, @summary.id, format: 'csv'), class: 'btn btn-primary float-right' do %>
                  <i class='fa fa-download'></i> Export Discrepancy Report
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <div class="white-box">

                  <span>Source Files: <%= value_data['total-source-files'] %></span>
                  <br>
                  <span>Destination Files: <%= value_data['total-destination-files'] %></span>
                  <br>
                  <span>Amount Discrepancies: <%= value_data['reconcile-amount-discrepancies'] %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-md-12">
      <div class="white-box">
        <div class="row">
          <div class="col-sm-12">
            <div class="white-box">
              Summary is not available.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>